version: "3.9"
services:
  letters-server:
    build:
      context: ./ascii-server
      tags:
        - "letters-server:v1"
    container_name: letters-server
    ports:
      - "8081:8081"

  numbers-server:
    build:
      context: ./ascii-server
      tags:
        - "numbers-server:v1"
    container_name: numbers-server
    environment:
      - NUMBERS_ONLY=true
    ports:
      - "8082:8081"

  ascii-requester:
    build:
      context: ./asciirequester
    container_name: ascii-requester
    depends_on:
      - letters-server
      - numbers-server
    environment:
      - LETTERS_ADDRESS=letters-server
      - LETTERS_PORT=8081
      - NUMBERS_ADDRESS=numbers-server
      - NUMBERS_PORT=8081
